
# Publishing images to GitHub Packages
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
# How to Publish a Docker Image to GitHub's Container Registry

# Sample workflow / Dockerfile setup for passing variables to build context (and the final binary)
# https://github.com/SchrodingersGat/InvenTree/blob/c34b7802b8d08f4165371f9479548dc0024f5042/.github/workflows/docker.yaml


# Get the current pushed tag in Github Actions
# https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions

name: Publish

env:
  REGISTRY: ghcr.io  # Must be set to ghcr.io.
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    tags:
      - v*

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          #  You can use the ${{ github.actor }} context to automatically use the username of the user that triggered the workflow run.
          username: ${{ github.actor }}
          # You can use the automatically-generated GITHUB_TOKEN secret for the password
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Store Git info in Environment
        run: |
          # tag can be extracted from GITHUB_REF which contains the checked out ref, e.g. refs/tags/v1.2.3
          echo "git_commit_tag=${GITHUB_REF#refs/*/}"                   >> $GITHUB_ENV
          echo "git_commit_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "git_commit_date=$(git show -s --format=%ci)"            >> $GITHUB_ENV
          echo "build_date=$(date +'%Y-%m-%dT%H:%M:%S')"          >> $GITHUB_ENV

      - name: Set up Docker Buildx for Multiple platform builds
        uses: docker/setup-buildx-action@v2.9.1

      # for multi platforms check https://docs.docker.com/build/ci/github-actions/multi-platform/
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          # CAUTION: platform: (...) requires docker/setup-buildx-action or you get
          # ERROR: Multiple platforms feature is currently not supported for docker driver. (...)
          # https://github.com/docker/build-push-action/issues/302
          platforms: linux/amd64,linux/arm64  # linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            commit_hash=${{ env.git_commit_hash }}
            commit_date=${{ env.git_commit_date }}
            commit_tag=${{ env.git_commit_tag }}
            build_date=${{ env.build_date }}
